import { useEffect, useState } from "react";
import { FileText, Download, Calendar, FileSpreadsheet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const Reports = () => {
  const [reports, setReports] = useState<any[]>([]);

  useEffect(() => {
    const fetchReports = async () => {
      // Fetch completed analyses from analysis_results, joined with uploads for filename
      const { data, error } = await supabase
        .from('analysis_results')
        .select(`
          *,
          uploads (
            filename,
            original_name
          )
        `)
        .order('created_at', { ascending: false });

      if (error) {
        console.error("Error fetching reports:", error);
      } else {
        setReports(data || []);
      }
    };
    fetchReports();
  }, []);

  const handleDownloadCSV = (report: any) => {
    try {
      if (!report.taxa || report.taxa.length === 0) {
        toast.error("No data available to download for this report.");
        return;
      }

      // 1. Convert JSON to CSV
      const items = report.taxa;
      const replacer = (key: string, value: any) => value === null ? '' : value;
      const header = Object.keys(items[0]);

      const csv = [
        header.join(','), // header row
        ...items.map((row: any) => header.map(fieldName => JSON.stringify(row[fieldName], replacer)).join(','))
      ].join('\r\n');

      // 2. Create Blob and Link
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');

      // 3. Trigger Download
      const filename = report.uploads?.original_name
        ? `Analysis_Report_${report.uploads.original_name}.csv`
        : `Analysis_Report_${report.id.slice(0, 8)}.csv`;

      a.setAttribute('hidden', '');
      a.setAttribute('href', url);
      a.setAttribute('download', filename);
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);

      toast.success(`Downloaded ${filename}`);
    } catch (e) {
      console.error("Download failed:", e);
      toast.error("Failed to generate CSV file.");
    }
  };

  const handlePrintPDF = (report: any) => {
    try {
      if (!report.taxa || report.taxa.length === 0) {
        toast.error("No data available to print.");
        return;
      }

      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error("Please allow popups to generate PDF.");
        return;
      }

      const title = report.uploads?.original_name || `Analysis Report ${report.id.slice(0, 8)}`;
      const date = new Date(report.created_at).toLocaleDateString();

      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #000; border-bottom: 2px solid #00CCCC; padding-bottom: 10px; }
            .header-info { margin-bottom: 30px; font-size: 14px; color: #666; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; font-weight: bold; }
            tr:nth-child(even) { background-color: #fafafa; }
            .footer { margin-top: 40px; font-size: 10px; text-align: center; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
          </style>
        </head>
        <body>
          <h1>Analysis Report</h1>
          <div class="header-info">
            <p><strong>File:</strong> ${title}</p>
            <p><strong>Date:</strong> ${date}</p>
            <p><strong>Species Count:</strong> ${report.taxa.length}</p>
          </div>
          
          <table>
            <thead>
              <tr>
                <th>Species</th>
                <th>Confidence</th>
                <th>Class</th>
                <th>Sequence Snippet</th>
              </tr>
            </thead>
            <tbody>
              ${report.taxa.map((t: any) => `
                <tr>
                  <td>${t.predicted_taxa || t.species || 'Unknown'}</td>
                  <td>${(t.confidence * 100).toFixed(1)}%</td>
                  <td>${t.class || 'N/A'}</td>
                  <td style="font-family: monospace;">${t.sequence_snippet || 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by SAGAR eDNA Analysis Platform
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
        </html>
      `;

      printWindow.document.write(htmlContent);
      printWindow.document.close();
    } catch (e) {
      console.error("Print failed:", e);
      toast.error("Failed to generate PDF view.");
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-display font-bold neon-text mb-2">Analysis Reports</h1>
        <p className="text-muted-foreground">Download analysis reports in PDF or CSV format.</p>
      </div>

      <div className="grid gap-4">
        {reports.length > 0 ? reports.map((report) => (
          <div key={report.id} className="glass-card p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-full bg-primary/10">
                <FileSpreadsheet className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-lg">
                  {report.uploads?.original_name || report.uploads?.filename || `Analysis ${report.id.slice(0, 8)}`}
                </h3>
                <div className="flex items-center gap-3 text-sm text-muted-foreground mt-1">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5" />
                    {new Date(report.created_at).toLocaleDateString()}
                  </span>
                  <span className="px-2 py-0.5 rounded-full bg-muted/50 border border-border/50 text-xs">
                    {report.taxa ? `${report.taxa.length} Species Found` : 'No Species Data'}
                  </span>
                  <span className="px-2 py-0.5 rounded-full bg-green-500/10 text-green-500 text-xs border border-green-500/20">
                    Completed
                  </span>
                </div>
              </div>
            </div>

            <div className="flex gap-2">
              <Button
                onClick={() => handlePrintPDF(report)}
                className="bg-white text-primary hover:bg-gray-100 border border-border gap-2 w-full md:w-auto"
                variant="outline"
                disabled={!report.taxa || report.taxa.length === 0}
              >
                <FileText className="w-4 h-4" />
                PDF
              </Button>
              <Button
                onClick={() => handleDownloadCSV(report)}
                className="btn-ocean gap-2 w-full md:w-auto"
                disabled={!report.taxa || report.taxa.length === 0}
              >
                <Download className="w-4 h-4" />
                CSV
              </Button>
            </div>
          </div>
        )) : (
          <div className="glass-card p-12 text-center border-dashed">
            <FileText className="w-12 h-12 mx-auto text-muted-foreground mb-4 opacity-50" />
            <h3 className="text-xl font-semibold mb-2">No Reports Available</h3>
            <p className="text-muted-foreground max-w-md mx-auto">
              Upload and analyze FASTA/FASTQ files to generate downloadable analysis reports.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Reports;
